image: cirrusci/flutter:stable


stages:
  - build


build:


  stage: build


  script:
    - flutter pub get
    - flutter clean
    - flutter build apk

  artifacts:
    paths:
    - build/app/outputs/flutter-apk/app-release.apk
