name: curativecare
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  html: ^0.14.0+3
  shimmer: ^1.1.1
  geolocator: ^5.3.2+2
  location: ^3.0.0
  bloc: ^4.0.0
  flutter_bloc: ^4.0.1
  equatable: ^1.2.0
  cached_network_image: ^2.2.0+1
  file_utils: ^0.1.4
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5
  dio: ^3.0.9
  permission_handler: ^5.0.0+hotfix.5
  csv: ^4.0.3

dependency_overrides:
  dartx: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Source
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 300
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
